<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>我的个人主页</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background: #f0f8ff;
            text-align: center;
            padding: 50px;
        }
        h1 {
            color: #2c3e50;
        }
        h2 {
            color: #3498db;
        }
        p {
            font-size: 18px;
            color: #555;
        }
    </style>
</head>
<body>
    <h1>你好，我是 侯强</h1>
    <h2>一名大学生</h2>
    <p>欢迎来到我的个人主页！我正在学习编程，希望未来成为一名开发者。</p>
</body>
</html>
